apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName }}
  labels:
    app: {{ .Values.appName }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.activeProfile }}
  SPRING_CLOUD_KUBERNETES_DISCOVERY_DISCOVERY_SERVER_URL: {{ .Values.global.discoveryServerURL }}
  SPRING_CONFIG_IMPORT: {{ .Values.global.configServerURL }}
  KEYCLOAK_URL: {{ .Values.global.keyCloakURL }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.global.otelExporterEndPoint }}
  OTEL_METRICS_EXPORTER: {{ .Values.global.otelMetricsExporter }}
  OTEL_LOGS_EXPORTER: {{ .Values.global.otelLogsExporter }}
  KAFKA_BROKER_URL: {{ .Values.global.kafkaBrokerURL }}
