# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#this act as key and value and same will be accessed by the eazybank-common heml chart.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: pdcourse/accounts #image name
  tag: s17 #image tag

containerPort: 8080 #container port

service:
  type: ClusterIP #as we don't want to expose the accounts MS outside of kubernetes cluster hence we are using service type as clusterIP
  port: 8080 #
  targetPort: 8080

#required enviornment varaibles for accounts MS. as we are checking if condition in eazybank-common before passing the environment variable to the MS.
appname_enabled: true
profile_enabled: true
config_enabled: true
# eureka_enabled: true
discovery_enabled: true
resouceserver_enabled: false #keycloak related. as only gatewayserver need it. and all other MS does not need it.
otel_enabled: true
kafka_enabled: true